---
# Productivity / communication / media apps (more personal — review per machine).
- name: Productivity & comms apps — casks
  community.general.homebrew_cask:
    name: "{{ item }}"
    state: present
  loop:
    - firefox
    - microsoft-teams
    - microsoft-outlook
    - microsoft-excel
    - microsoft-word
    - onedrive
    - zoom
    - raycast # screen manager, utility, launcher, ...
    # - discord
    # - grammarly-desktop
    # - vlc
    # - gimp
    # - balenaetcher
